package com.rec.movie.domain;

import lombok.Data;

import java.util.Date;

@Data
public class Movieinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.movieid
     *
     * @mbggenerated
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.moviename
     *
     * @mbggenerated
     */
    private String moviename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.releasetime
     *
     * @mbggenerated
     */
    private Date releasetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.director
     *
     * @mbggenerated
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.leadactors
     *
     * @mbggenerated
     */
    private String leadactors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.averating
     *
     * @mbggenerated
     */
    private Double averating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.numrating
     *
     * @mbggenerated
     */
    private Integer numrating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.typelist
     *
     * @mbggenerated
     */
    private String typelist;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieinfo
     *
     * @mbggenerated
     */
    public Movieinfo(Integer movieid, String moviename, Date releasetime, String director, String leadactors, String picture, Double averating, Integer numrating, String description, String typelist) {
        this.movieid = movieid;
        this.moviename = moviename;
        this.releasetime = releasetime;
        this.director = director;
        this.leadactors = leadactors;
        this.picture = picture;
        this.averating = averating;
        this.numrating = numrating;
        this.description = description;
        this.typelist = typelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieinfo
     *
     * @mbggenerated
     */
    public Movieinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.movieid
     *
     * @return the value of movieinfo.movieid
     *
     * @mbggenerated
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.movieid
     *
     * @param movieid the value for movieinfo.movieid
     *
     * @mbggenerated
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.moviename
     *
     * @return the value of movieinfo.moviename
     *
     * @mbggenerated
     */
    public String getMoviename() {
        return moviename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.moviename
     *
     * @param moviename the value for movieinfo.moviename
     *
     * @mbggenerated
     */
    public void setMoviename(String moviename) {
        this.moviename = moviename == null ? null : moviename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.releasetime
     *
     * @return the value of movieinfo.releasetime
     *
     * @mbggenerated
     */
    public Date getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.releasetime
     *
     * @param releasetime the value for movieinfo.releasetime
     *
     * @mbggenerated
     */
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.director
     *
     * @return the value of movieinfo.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.director
     *
     * @param director the value for movieinfo.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.leadactors
     *
     * @return the value of movieinfo.leadactors
     *
     * @mbggenerated
     */
    public String getLeadactors() {
        return leadactors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.leadactors
     *
     * @param leadactors the value for movieinfo.leadactors
     *
     * @mbggenerated
     */
    public void setLeadactors(String leadactors) {
        this.leadactors = leadactors == null ? null : leadactors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.picture
     *
     * @return the value of movieinfo.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.picture
     *
     * @param picture the value for movieinfo.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.averating
     *
     * @return the value of movieinfo.averating
     *
     * @mbggenerated
     */
    public Double getAverating() {
        return averating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.averating
     *
     * @param averating the value for movieinfo.averating
     *
     * @mbggenerated
     */
    public void setAverating(Double averating) {
        this.averating = averating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.numrating
     *
     * @return the value of movieinfo.numrating
     *
     * @mbggenerated
     */
    public Integer getNumrating() {
        return numrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.numrating
     *
     * @param numrating the value for movieinfo.numrating
     *
     * @mbggenerated
     */
    public void setNumrating(Integer numrating) {
        this.numrating = numrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.description
     *
     * @return the value of movieinfo.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.description
     *
     * @param description the value for movieinfo.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.typelist
     *
     * @return the value of movieinfo.typelist
     *
     * @mbggenerated
     */
    public String getTypelist() {
        return typelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.typelist
     *
     * @param typelist the value for movieinfo.typelist
     *
     * @mbggenerated
     */
    public void setTypelist(String typelist) {
        this.typelist = typelist == null ? null : typelist.trim();
    }
}