package com.rec.movie.domain;

import com.baomidou.mybatisplus.annotation.TableField;
import lombok.Data;

@Data
public class Personalratings {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personalratings.userid
     *
     * @mbggenerated
     */


    /*@TableField("id")
    private String id;*/

    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personalratings.movieid
     *
     * @mbggenerated
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personalratings.rating
     *
     * @mbggenerated
     */
    private Integer rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personalratings.timestamp
     *
     * @mbggenerated
     */
    private String timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalratings
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalratings
     *
     * @mbggenerated
     */
    public Personalratings() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personalratings.userid
     *
     * @return the value of personalratings.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personalratings.userid
     *
     * @param userid the value for personalratings.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personalratings.movieid
     *
     * @return the value of personalratings.movieid
     *
     * @mbggenerated
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personalratings.movieid
     *
     * @param movieid the value for personalratings.movieid
     *
     * @mbggenerated
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personalratings.rating
     *
     * @return the value of personalratings.rating
     *
     * @mbggenerated
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personalratings.rating
     *
     * @param rating the value for personalratings.rating
     *
     * @mbggenerated
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personalratings.timestamp
     *
     * @return the value of personalratings.timestamp
     *
     * @mbggenerated
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personalratings.timestamp
     *
     * @param timestamp the value for personalratings.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }
}