package com.rec.movie.domain;

import lombok.Data;

@Data
public class Recommendresult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommendresult.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommendresult.movieid
     *
     * @mbggenerated
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommendresult.rating
     *
     * @mbggenerated
     */
    private Float rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommendresult.moviename
     *
     * @mbggenerated
     */
    private String moviename;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommendresult
     *
     * @mbggenerated
     */
    public Recommendresult(Integer userid, Integer movieid, Float rating, String moviename) {
        this.userid = userid;
        this.movieid = movieid;
        this.rating = rating;
        this.moviename = moviename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommendresult
     *
     * @mbggenerated
     */
    public Recommendresult() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommendresult.userid
     *
     * @return the value of recommendresult.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommendresult.userid
     *
     * @param userid the value for recommendresult.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommendresult.movieid
     *
     * @return the value of recommendresult.movieid
     *
     * @mbggenerated
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommendresult.movieid
     *
     * @param movieid the value for recommendresult.movieid
     *
     * @mbggenerated
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommendresult.rating
     *
     * @return the value of recommendresult.rating
     *
     * @mbggenerated
     */
    public Float getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommendresult.rating
     *
     * @param rating the value for recommendresult.rating
     *
     * @mbggenerated
     */
    public void setRating(Float rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommendresult.moviename
     *
     * @return the value of recommendresult.moviename
     *
     * @mbggenerated
     */
    public String getMoviename() {
        return moviename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommendresult.moviename
     *
     * @param moviename the value for recommendresult.moviename
     *
     * @mbggenerated
     */
    public void setMoviename(String moviename) {
        this.moviename = moviename == null ? null : moviename.trim();
    }
}